# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
<<<<<<< HEAD
  secret_key_base: e35cdccefab8d915d79a2d176fae5c60d4f467eb41d0b5c63533365ab55d44132230e55f7943ba0a7e08cd54e570a4019f7fd72c90288141de32b26f1e56bfe6

test:
  secret_key_base: e31be08ac9047e6ac4ec8043ef7157259e492bacc724713e50899fe0fa21d49e8939bab34fa1dc533cc8c53f90da05aa89023cb7b89597bf9a45264d39cf2e1d
=======
  secret_key_base: 0c8fd1eb2caee00dc0a23f0e684b72909c73d342fc1ca450d4e55ac637c352d49038fc61bed848c3330885b8c87acbca4641e8049fd4381dc743850d565f8614

test:
  secret_key_base: f6c6a098473e75dc825fc22420ab4dc0275764b7608426962be6df1c4affca09b4bf370ddd1ecf7bddeb0e70d92d0e9dcbcfc512a392ac6df3b8bb43b1f40e4c
>>>>>>> 2335db8cf13bad5c4a249ed117a9ecb5e3d21a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
